name: ci-gtest-workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir -p build && cd build && cmake ../
    - name: make
      run: cd build && make
    - name: Run Test
      run: /home/runner/work/VDSProject_Group_8/VDSProject_Group_8/build/src/test/VDSProject_test
